/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DisplayType } from "./components/label/_utils";
export namespace Components {
    interface EsriDs2022Clustering {
        /**
          * arcgis/core/layers/FeatureLayer: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html
         */
        "layer": __esri.FeatureLayer;
        /**
          * arcgis/core/views/MapView: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html
         */
        "mapView": __esri.MapView;
    }
    interface EsriDs2022Label {
        "displayType": DisplayType;
        "labelPanel"?: HTMLCalcitePanelElement;
        /**
          * arcgis/core/layers/FeatureLayer: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html
         */
        "layer": __esri.FeatureLayer;
        /**
          * arcgis/core/views/MapView: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html
         */
        "mapView": __esri.MapView;
    }
    interface EsriDs2022LabelContent {
        "displayType": DisplayType;
        "labelClass": __esri.LabelClass;
        "layer": __esri.FeatureLayer;
        "mapView": __esri.MapView;
    }
    interface EsriDs2022LabelContentStyle {
        "labelClass": __esri.LabelClass;
        "labelContentRefElement": HTMLElement;
    }
    interface EsriDs2022Map {
        "title": string;
    }
}
declare global {
    interface HTMLEsriDs2022ClusteringElement extends Components.EsriDs2022Clustering, HTMLStencilElement {
    }
    var HTMLEsriDs2022ClusteringElement: {
        prototype: HTMLEsriDs2022ClusteringElement;
        new (): HTMLEsriDs2022ClusteringElement;
    };
    interface HTMLEsriDs2022LabelElement extends Components.EsriDs2022Label, HTMLStencilElement {
    }
    var HTMLEsriDs2022LabelElement: {
        prototype: HTMLEsriDs2022LabelElement;
        new (): HTMLEsriDs2022LabelElement;
    };
    interface HTMLEsriDs2022LabelContentElement extends Components.EsriDs2022LabelContent, HTMLStencilElement {
    }
    var HTMLEsriDs2022LabelContentElement: {
        prototype: HTMLEsriDs2022LabelContentElement;
        new (): HTMLEsriDs2022LabelContentElement;
    };
    interface HTMLEsriDs2022LabelContentStyleElement extends Components.EsriDs2022LabelContentStyle, HTMLStencilElement {
    }
    var HTMLEsriDs2022LabelContentStyleElement: {
        prototype: HTMLEsriDs2022LabelContentStyleElement;
        new (): HTMLEsriDs2022LabelContentStyleElement;
    };
    interface HTMLEsriDs2022MapElement extends Components.EsriDs2022Map, HTMLStencilElement {
    }
    var HTMLEsriDs2022MapElement: {
        prototype: HTMLEsriDs2022MapElement;
        new (): HTMLEsriDs2022MapElement;
    };
    interface HTMLElementTagNameMap {
        "esri-ds2022-clustering": HTMLEsriDs2022ClusteringElement;
        "esri-ds2022-label": HTMLEsriDs2022LabelElement;
        "esri-ds2022-label-content": HTMLEsriDs2022LabelContentElement;
        "esri-ds2022-label-content-style": HTMLEsriDs2022LabelContentStyleElement;
        "esri-ds2022-map": HTMLEsriDs2022MapElement;
    }
}
declare namespace LocalJSX {
    interface EsriDs2022Clustering {
        /**
          * arcgis/core/layers/FeatureLayer: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html
         */
        "layer"?: __esri.FeatureLayer;
        /**
          * arcgis/core/views/MapView: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html
         */
        "mapView"?: __esri.MapView;
        /**
          * Emitted when featureReduction has been updated.
         */
        "onFeatureReductionUpdated"?: (event: CustomEvent<any>) => void;
        "onInternalFeatureReductionUpdated"?: (event: CustomEvent<any>) => void;
    }
    interface EsriDs2022Label {
        "displayType"?: DisplayType;
        "labelPanel"?: HTMLCalcitePanelElement;
        /**
          * arcgis/core/layers/FeatureLayer: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html
         */
        "layer"?: __esri.FeatureLayer;
        /**
          * arcgis/core/views/MapView: https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html
         */
        "mapView"?: __esri.MapView;
        "onCloseLabelPopovers"?: (event: CustomEvent<any>) => void;
        "onInternalLabelUpdated"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when label has been updated.
         */
        "onLabelUpdated"?: (event: CustomEvent<any>) => void;
    }
    interface EsriDs2022LabelContent {
        "displayType"?: DisplayType;
        "labelClass"?: __esri.LabelClass;
        "layer"?: __esri.FeatureLayer;
        "mapView"?: __esri.MapView;
        "onCloseLabelPopovers"?: (event: CustomEvent<any>) => void;
        "onDisableLabelPanel"?: (event: CustomEvent<any>) => void;
        "onInternalLabelUpdated"?: (event: CustomEvent<any>) => void;
        "onLabelContentDeleted"?: (event: CustomEvent<any>) => void;
    }
    interface EsriDs2022LabelContentStyle {
        "labelClass"?: __esri.LabelClass;
        "labelContentRefElement"?: HTMLElement;
        "onCloseLabelPopovers"?: (event: CustomEvent<any>) => void;
        "onLabelContentStyleChanges"?: (event: CustomEvent<any>) => void;
    }
    interface EsriDs2022Map {
        "title"?: string;
    }
    interface IntrinsicElements {
        "esri-ds2022-clustering": EsriDs2022Clustering;
        "esri-ds2022-label": EsriDs2022Label;
        "esri-ds2022-label-content": EsriDs2022LabelContent;
        "esri-ds2022-label-content-style": EsriDs2022LabelContentStyle;
        "esri-ds2022-map": EsriDs2022Map;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "esri-ds2022-clustering": LocalJSX.EsriDs2022Clustering & JSXBase.HTMLAttributes<HTMLEsriDs2022ClusteringElement>;
            "esri-ds2022-label": LocalJSX.EsriDs2022Label & JSXBase.HTMLAttributes<HTMLEsriDs2022LabelElement>;
            "esri-ds2022-label-content": LocalJSX.EsriDs2022LabelContent & JSXBase.HTMLAttributes<HTMLEsriDs2022LabelContentElement>;
            "esri-ds2022-label-content-style": LocalJSX.EsriDs2022LabelContentStyle & JSXBase.HTMLAttributes<HTMLEsriDs2022LabelContentStyleElement>;
            "esri-ds2022-map": LocalJSX.EsriDs2022Map & JSXBase.HTMLAttributes<HTMLEsriDs2022MapElement>;
        }
    }
}
